# Generated by Django 6.0.5 on 2026-06-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_de", models.CharField(max_length=255, null=True)),
                ("title_fr", models.CharField(max_length=255, null=True)),
                ("title_ja", models.CharField(max_length=255, null=True)),
                ("content", models.TextField(help_text="Markdown supported")),
                (
                    "content_en",
                    models.TextField(help_text="Markdown supported", null=True),
                ),
                (
                    "content_de",
                    models.TextField(help_text="Markdown supported", null=True),
                ),
                (
                    "content_fr",
                    models.TextField(help_text="Markdown supported", null=True),
                ),
                (
                    "content_ja",
                    models.TextField(help_text="Markdown supported", null=True),
                ),
                (
                    "date",
                    models.DateField(help_text="Publication date shown on the post"),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=True,
                        help_text="Draft news items are only visible to staff members.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News Item",
                "verbose_name_plural": "News Items",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
