# Generated by Django 6.0.5 on 2026-06-09 18:41

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=markdownx.models.MarkdownxField(help_text="Markdown supported"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_de",
            field=markdownx.models.MarkdownxField(
                help_text="Markdown supported", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_en",
            field=markdownx.models.MarkdownxField(
                help_text="Markdown supported", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_fr",
            field=markdownx.models.MarkdownxField(
                help_text="Markdown supported", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_ja",
            field=markdownx.models.MarkdownxField(
                help_text="Markdown supported", null=True
            ),
        ),
    ]
