# Generated by Django 6.0.4 on 2026-04-16 19:33

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_de",
            field=markdownx.models.MarkdownxField(null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_en",
            field=markdownx.models.MarkdownxField(null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_fr",
            field=markdownx.models.MarkdownxField(null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_ja",
            field=markdownx.models.MarkdownxField(null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_de",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ja",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
