# Generated by Django 6.0.5 on 2026-05-30 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogIndexPage",
        ),
    ]
