# Generated by Django 6.0.5 on 2026-05-10 09:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_template": "wagtailadmin/block_forms/heading.html",
                            "icon": "title",
                        },
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image"},
                    ),
                },
            ),
        ),
    ]
