# Generated by Django 6.0.5 on 2026-05-10 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blogpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogindexpage",
            name="intro",
        ),
    ]
