# Generated by Django 6.0.5 on 2026-06-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blogpost_content_alter_blogpost_content_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image for the blog post",
                null=True,
                upload_to="blog_covers/",
                verbose_name="Cover Image",
            ),
        ),
    ]
