# Generated by Django 6.0.2 on 2026-02-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_brand_description_de_brand_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Stripe Name"
            ),
        ),
    ]
