# Generated by Django 6.0.2 on 2026-02-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_product_stripe_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
    ]
