# Generated by Django 6.0.2 on 2026-02-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_product_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="public",
            field=models.BooleanField(default=True, verbose_name="Public"),
        ),
    ]
