# Generated by Django 6.0.2 on 2026-02-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_product_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_ja",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Product Type",
                "verbose_name_plural": "Product Types",
            },
        ),
        migrations.CreateModel(
            name="Yakikata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_ja",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Yakikata",
                "verbose_name_plural": "Yakikatas",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Product Type"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="yakikata",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Yakikata"
            ),
        ),
    ]
