# Generated by Django 6.0.2 on 2026-02-28 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_producttype_yakikata_alter_product_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.producttype",
                verbose_name="Product Type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="yakikata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.yakikata",
                verbose_name="Yakikata",
            ),
        ),
    ]
