# Generated by Django 6.0.2 on 2026-03-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_alter_product_product_type_alter_product_yakikata"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Announcement Text")),
                (
                    "text_en",
                    models.TextField(null=True, verbose_name="Announcement Text"),
                ),
                (
                    "text_de",
                    models.TextField(null=True, verbose_name="Announcement Text"),
                ),
                (
                    "text_fr",
                    models.TextField(null=True, verbose_name="Announcement Text"),
                ),
                (
                    "text_ja",
                    models.TextField(null=True, verbose_name="Announcement Text"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is Active"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store Announcement",
                "verbose_name_plural": "Store Announcements",
            },
        ),
    ]
