# Generated by Django 6.0.2 on 2026-03-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_storeannouncement"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="craftsmanship_body",
            field=models.TextField(blank=True, verbose_name="The Craft"),
        ),
        migrations.AddField(
            model_name="brand",
            name="craftsmanship_body_de",
            field=models.TextField(blank=True, null=True, verbose_name="The Craft"),
        ),
        migrations.AddField(
            model_name="brand",
            name="craftsmanship_body_en",
            field=models.TextField(blank=True, null=True, verbose_name="The Craft"),
        ),
        migrations.AddField(
            model_name="brand",
            name="craftsmanship_body_fr",
            field=models.TextField(blank=True, null=True, verbose_name="The Craft"),
        ),
        migrations.AddField(
            model_name="brand",
            name="craftsmanship_body_ja",
            field=models.TextField(blank=True, null=True, verbose_name="The Craft"),
        ),
        migrations.AddField(
            model_name="brand",
            name="hero_image",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Hero Image URL"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="Location"),
        ),
        migrations.AddField(
            model_name="brand",
            name="location_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="location_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="location_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="location_ja",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="story_body",
            field=models.TextField(blank=True, verbose_name="The Story"),
        ),
        migrations.AddField(
            model_name="brand",
            name="story_body_de",
            field=models.TextField(blank=True, null=True, verbose_name="The Story"),
        ),
        migrations.AddField(
            model_name="brand",
            name="story_body_en",
            field=models.TextField(blank=True, null=True, verbose_name="The Story"),
        ),
        migrations.AddField(
            model_name="brand",
            name="story_body_fr",
            field=models.TextField(blank=True, null=True, verbose_name="The Story"),
        ),
        migrations.AddField(
            model_name="brand",
            name="story_body_ja",
            field=models.TextField(blank=True, null=True, verbose_name="The Story"),
        ),
        migrations.AddField(
            model_name="brand",
            name="story_side_image",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Story Side Image URL"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="wares_summary",
            field=models.TextField(blank=True, verbose_name="The Wares"),
        ),
        migrations.AddField(
            model_name="brand",
            name="wares_summary_de",
            field=models.TextField(blank=True, null=True, verbose_name="The Wares"),
        ),
        migrations.AddField(
            model_name="brand",
            name="wares_summary_en",
            field=models.TextField(blank=True, null=True, verbose_name="The Wares"),
        ),
        migrations.AddField(
            model_name="brand",
            name="wares_summary_fr",
            field=models.TextField(blank=True, null=True, verbose_name="The Wares"),
        ),
        migrations.AddField(
            model_name="brand",
            name="wares_summary_ja",
            field=models.TextField(blank=True, null=True, verbose_name="The Wares"),
        ),
        migrations.CreateModel(
            name="BrandImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="Image URL")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Caption"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="shop.brand",
                        verbose_name="Brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Image",
                "verbose_name_plural": "Brand Images",
                "ordering": ["order"],
            },
        ),
    ]
