# Generated by Django 6.0.3 on 2026-03-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_brand_craftsmanship_body_brand_craftsmanship_body_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_paused",
                    models.BooleanField(default=False, verbose_name="Sales Paused"),
                ),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
    ]
