# Generated by Django 6.0.3 on 2026-03-16 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_storesettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
    ]
