# Generated by Django 6.0.3 on 2026-03-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_brand_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Yakikata",
            new_name="Glaze",
        ),
        migrations.AlterModelOptions(
            name="glaze",
            options={"verbose_name": "Glaze", "verbose_name_plural": "Glazes"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="yakikata",
        ),
        migrations.AddField(
            model_name="product",
            name="glaze",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.glaze",
                verbose_name="Glaze",
            ),
        ),
    ]
