# Generated by Django 6.0.3 on 2026-04-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_populate_glazes"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_images/",
                verbose_name="Image File",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Image URL"),
        ),
    ]
