# Generated by Django 6.0.5 on 2026-05-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_remove_brand_craftsmanship_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="carousel/", verbose_name="Image"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Carousel Image",
                "verbose_name_plural": "Carousel Images",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
