# Generated by Django 6.0.5 on 2026-05-25 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_carouselimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carouselimage",
            name="title",
        ),
    ]
