# Generated by Django 6.0.5 on 2026-05-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_remove_carouselimage_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="content_slug",
            field=models.SlugField(
                blank=True,
                help_text="The slug for the static markdown page (e.g., bizen)",
                max_length=255,
                verbose_name="Content Slug",
            ),
        ),
    ]
