# Generated by Django 6.0.5 on 2026-05-27 19:57

from django.db import migrations


def strip_brands_prefix(apps, schema_editor):
    Brand = apps.get_model("shop", "Brand")
    for brand in Brand.objects.all():
        if brand.content_slug and brand.content_slug.startswith("brands/"):
            brand.content_slug = brand.content_slug.replace("brands/", "", 1)
            brand.save()


def restore_brands_prefix(apps, schema_editor):
    Brand = apps.get_model("shop", "Brand")
    for brand in Brand.objects.all():
        if brand.content_slug and not brand.content_slug.startswith("brands/"):
            brand.content_slug = f"brands/{brand.content_slug}"
            brand.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_alter_brand_content_slug"),
    ]

    operations = [
        migrations.RunPython(strip_brands_prefix, restore_brands_prefix),
    ]
