# Generated by Django 6.0.5 on 2026-05-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0019_strip_brands_prefix_from_content_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.TextField(blank=True, verbose_name="Details"),
        ),
        migrations.AddField(
            model_name="product",
            name="details_de",
            field=models.TextField(blank=True, null=True, verbose_name="Details"),
        ),
        migrations.AddField(
            model_name="product",
            name="details_en",
            field=models.TextField(blank=True, null=True, verbose_name="Details"),
        ),
        migrations.AddField(
            model_name="product",
            name="details_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Details"),
        ),
        migrations.AddField(
            model_name="product",
            name="details_ja",
            field=models.TextField(blank=True, null=True, verbose_name="Details"),
        ),
    ]
