# Generated by Django 6.0.5 on 2026-06-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0020_product_details_product_details_de_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="main_photo",
            new_name="_main_photo_temp",
        ),
        migrations.AlterField(
            model_name="product",
            name="_main_photo_temp",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Main Photo URL (Temp)",
            ),
        ),
    ]
