# Generated by Django 6.0.5 on 2026-06-07 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0022_migrate_main_photo_to_gallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="_main_photo_temp",
        ),
    ]
