# Generated by Django 6.0.5 on 2026-06-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0023_remove_main_photo_temp"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Internal path (e.g. /shop/) or external URL",
                max_length=500,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="link_de",
            field=models.CharField(
                blank=True,
                help_text="Internal path (e.g. /shop/) or external URL",
                max_length=500,
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="link_en",
            field=models.CharField(
                blank=True,
                help_text="Internal path (e.g. /shop/) or external URL",
                max_length=500,
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="link_fr",
            field=models.CharField(
                blank=True,
                help_text="Internal path (e.g. /shop/) or external URL",
                max_length=500,
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="link_ja",
            field=models.CharField(
                blank=True,
                help_text="Internal path (e.g. /shop/) or external URL",
                max_length=500,
                null=True,
                verbose_name="Link",
            ),
        ),
    ]
