# Generated by Django 6.0.5 on 2026-06-07 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0024_carouselimage_link_carouselimage_link_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carouselimage",
            name="link_de",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="link_en",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="link_fr",
        ),
        migrations.RemoveField(
            model_name="carouselimage",
            name="link_ja",
        ),
    ]
