# Generated by Django 6.0.5 on 2026-06-07 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0025_remove_carouselimage_link_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carouselimage",
            name="is_active",
        ),
    ]
