# Generated by Django 6.0.5 on 2026-06-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0026_remove_carouselimage_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="Alt Text"),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="alt_text_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="alt_text_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="alt_text_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="alt_text_ja",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Alt Text"
            ),
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="overlay_image",
            field=models.FileField(
                blank=True,
                help_text="Optional SVG overlay centered horizontally and stuck to the right.",
                null=True,
                upload_to="carousel/overlays/",
                verbose_name="Overlay Image",
            ),
        ),
    ]
