# Generated by Django 6.0.5 on 2026-06-09 18:42

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0027_carouselimage_alt_text_carouselimage_alt_text_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_de",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_fr",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ja",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="details",
            field=markdownx.models.MarkdownxField(blank=True, verbose_name="Details"),
        ),
        migrations.AlterField(
            model_name="product",
            name="details_de",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Details"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="details_en",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Details"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="details_fr",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Details"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="details_ja",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="Details"
            ),
        ),
    ]
