# Generated by Django 6.0.5 on 2026-06-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0028_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="soon_in_stock",
            field=models.BooleanField(default=False, verbose_name="Soon in stock"),
        ),
    ]
